# -*- coding: utf-8 -*-
"""analyse de qualité du vin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w87At3qO7-qwmrDtpRSQ3ONoQuaKEUGF
"""

pip install ucimlrepo

"""Dans cette première partie, nous installons la bibliothèque ucimlrepo qui permet de récupérer facilement des jeux de données de l’UCI Machine Learning Repository. Nous importons ensuite les bibliothèques nécessaires pour la manipulation des données (pandas, numpy), la visualisation (matplotlib, seaborn) et le machine learning (scikit-learn)."""

from ucimlrepo import fetch_ucirepo

# fetch dataset
wine_quality = fetch_ucirepo(id=186)

# data (as pandas dataframes)
X = wine_quality.data.features
y = wine_quality.data.targets

# metadata
print(wine_quality.metadata)

# variable information
print(wine_quality.variables)

"""Cette partie permet de charger le dataset Wine Quality depuis l’UCI.
Nous obtenons N échantillons correspondant à des vins blancs, décrits chacun par d caractéristiques physico-chimiques (acidité, pH, alcool, etc.). La variable de sortie quality est une note entière, généralement entre 3 et 9. La répartition montre que certaines qualités sont beaucoup plus fréquentes que d’autres, ce qui indique un déséquilibre de classes.
"""

# ============================================================
# TP – Classification de la qualité de vin (winequality-white)
# ============================================================

# --- 0. Imports ---
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Pour des résultats reproductibles
RANDOM_STATE = 0

# ------------------------------------------------------------
# 1. Chargement des données et résumé
# ------------------------------------------------------------
link = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"

df = pd.read_csv(link, header="infer", delimiter=";")

print("\n========= Dataset summary =========\n")
df.info()

print("\n========= A few first samples =========\n")
display(df.head())

# ------------------------------------------------------------
# 2. Création de X, Y (multi-classes) puis Y binaire
# ------------------------------------------------------------
X = df.drop("quality", axis=1)   # variables explicatives
Y = df["quality"]                # note de qualité (3..9)

print("\n========= Wine Qualities (multi-classes) =========\n")
print(Y.value_counts().sort_index())

# Passage à un problème binaire :
#   y_bin = 0 si qualité <= 5 (mauvais vin)
#   y_bin = 1 sinon (bon vin)
Y_bin = np.array([0 if val <= 5 else 1 for val in Y])

print("\n========= Nombre d'échantillons par classe binaire =========\n")
unique, counts = np.unique(Y_bin, return_counts=True)
for c, n in zip(unique, counts):
    label = "mauvais vin (<=5)" if c == 0 else "bon vin (>5)"
    print(f"Classe {c} ({label}) : {n} échantillons")

print(f"\nNombre total d'échantillons : {len(Y_bin)}")
print(f"Nombre de variables d'entrée : {X.shape[1]}")

# ------------------------------------------------------------
# 3. Analyse statistique des variables
# ------------------------------------------------------------
print("\n========= Statistiques descriptives des variables =========\n")
display(X.describe())

# Boxplots de toutes les variables
plt.figure(figsize=(12, 6))
ax = sns.boxplot(data=X, orient="v", width=1.5)
ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
plt.title("Boxplots des caractéristiques physico-chimiques")
plt.tight_layout()
plt.show()

# Matrice de corrélation
plt.figure(figsize=(10, 8))
corr = X.corr()
sns.heatmap(corr, annot=False)
plt.title("Matrice de corrélation entre les variables")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 4. Découpage des données : apprentissage / validation / test
# ------------------------------------------------------------
Xa, Xt, Ya, Yt = train_test_split(
    X, Y_bin,
    test_size=1/3,
    shuffle=True,
    stratify=Y_bin,
    random_state=RANDOM_STATE
)

Xa, Xv, Ya, Yv = train_test_split(
    Xa, Ya,
    test_size=0.5,
    shuffle=True,
    stratify=Ya,
    random_state=RANDOM_STATE
)

print("\n========= Tailles des sous-ensembles =========\n")
print(f"Apprentissage : {Xa.shape[0]} échantillons")
print(f"Validation    : {Xv.shape[0]} échantillons")
print(f"Test          : {Xt.shape[0]} échantillons")

def print_class_dist(y, name):
    unique, counts = np.unique(y, return_counts=True)
    print(f"\n{name}:")
    for c, n in zip(unique, counts):
        print(f"  Classe {c} : {n} ({n/len(y):.2%})")

print_class_dist(Ya, "Apprentissage")
print_class_dist(Yv, "Validation")
print_class_dist(Yt, "Test")

# ------------------------------------------------------------
# 5. k-NN SANS normalisation : choix de k et erreur test
# ------------------------------------------------------------

k_vector = np.arange(1, 41, 2)  # k = 1,3,5,...,39
error_train = np.empty(k_vector.shape)
error_val = np.empty(k_vector.shape)

for ind, k in enumerate(k_vector):
    clf = KNeighborsClassifier(n_neighbors=k)
    clf.fit(Xa, Ya)

    # erreur sur apprentissage
    Ypred_train = clf.predict(Xa)
    error_train[ind] = 1 - accuracy_score(Ya, Ypred_train)

    # erreur sur validation
    Ypred_val = clf.predict(Xv)
    error_val[ind] = 1 - accuracy_score(Yv, Ypred_val)

# Courbes d’erreur
plt.figure(figsize=(8, 5))
plt.plot(k_vector, error_train, marker="o", label="Erreur apprentissage (brut)")
plt.plot(k_vector, error_val, marker="s", label="Erreur validation (brut)")
plt.xlabel("Nombre de voisins k")
plt.ylabel("Erreur de classification")
plt.title("k-NN sans normalisation")
plt.grid(True)
plt.legend()
plt.show()

# meilleur k sur la validation
err_min, ind_opt = error_val.min(), error_val.argmin()
k_star = k_vector[ind_opt]

print(f"\n[Sans normalisation] Meilleur k* = {k_star} avec erreur de validation = {err_min:.4f}")

# erreur finale sur le test
clf_best = KNeighborsClassifier(n_neighbors=k_star)
clf_best.fit(Xa, Ya)

Ypred_test = clf_best.predict(Xt)
error_test = 1 - accuracy_score(Yt, Ypred_test)

print(f"[Sans normalisation] Erreur finale sur le test = {error_test:.4f}")

# ------------------------------------------------------------
# 6. Normalisation des données + nouveau k-NN
# ------------------------------------------------------------

sc = StandardScaler(with_mean=True, with_std=True)
sc.fit(Xa)          # paramètres calculés uniquement sur l'apprentissage

Xa_n = sc.transform(Xa)
Xv_n = sc.transform(Xv)
Xt_n = sc.transform(Xt)

print("\nMoyenne (Xa normalisé, 5 premières variables) :", Xa_n.mean(axis=0)[:5])
print("Écart-type (Xa normalisé, 5 premières variables) :", Xa_n.std(axis=0)[:5])

# Balayage de k sur données normalisées
error_train_n = np.empty(k_vector.shape)
error_val_n = np.empty(k_vector.shape)

for ind, k in enumerate(k_vector):
    clf = KNeighborsClassifier(n_neighbors=k)
    clf.fit(Xa_n, Ya)

    Ypred_train_n = clf.predict(Xa_n)
    error_train_n[ind] = 1 - accuracy_score(Ya, Ypred_train_n)

    Ypred_val_n = clf.predict(Xv_n)
    error_val_n[ind] = 1 - accuracy_score(Yv, Ypred_val_n)

plt.figure(figsize=(8, 5))
plt.plot(k_vector, error_train_n, marker="o", label="Erreur apprentissage (normalisé)")
plt.plot(k_vector, error_val_n, marker="s", label="Erreur validation (normalisé)")
plt.xlabel("Nombre de voisins k")
plt.ylabel("Erreur de classification")
plt.title("k-NN avec données normalisées")
plt.grid(True)
plt.legend()
plt.show()

# meilleur k sur validation (normalisé)
err_min_n, ind_opt_n = error_val_n.min(), error_val_n.argmin()
k_star_n = k_vector[ind_opt_n]

print(f"\n[Avec normalisation] Meilleur k* = {k_star_n} avec erreur de validation = {err_min_n:.4f}")

# erreur finale sur test (normalisé)
clf_best_n = KNeighborsClassifier(n_neighbors=k_star_n)
clf_best_n.fit(Xa_n, Ya)

Ypred_test_n = clf_best_n.predict(Xt_n)
error_test_n = 1 - accuracy_score(Yt, Ypred_test_n)

print(f"[Avec normalisation] Erreur finale sur le test = {error_test_n:.4f}")

# ------------------------------------------------------------
# 7. Synthèse finale
# ------------------------------------------------------------
print("\n==================== Synthèse ====================")
print(f"Sans normalisation : k* = {k_star}, erreur test = {error_test:.4f}")
print(f"Avec normalisation : k* = {k_star_n}, erreur test = {error_test_n:.4f}")
print("==================================================")

"""Dans ce travail, nous avons étudié la prédiction de la qualité de vins blancs à partir de caractéristiques physico-chimiques. Après avoir chargé le jeu de données UCI Wine Quality et analysé sa structure (nombre d’échantillons, nombre de variables, statistiques descriptives, boxplots et corrélations), nous avons transformé le problème multi-classe initial en un problème binaire distinguant les vins de qualité faible (note ≤ 5) et les vins de meilleure qualité (note > 5). Le découpage du jeu de données en trois sous-ensembles (apprentissage, validation et test) avec stratification a permis de conserver les proportions de classes et d’évaluer honnêtement les performances du modèle.
Nous avons ensuite utilisé un classifieur des k plus proches voisins (k-NN) : en faisant varier k, nous avons observé le comportement de l’erreur sur l’apprentissage et sur la validation, ce qui met en évidence le compromis entre sur-apprentissage (k trop petit) et sous-apprentissage (k trop grand). Le meilleur k a été choisi en minimisant l’erreur de validation, puis la performance a été mesurée sur l’ensemble de test. La même procédure a été reproduite après normalisation des données (centrage-réduction), ce qui est important pour les méthodes basées sur la distance. La comparaison des erreurs de test avec et sans normalisation montre que la prise en compte correcte des échelles des variables peut améliorer la capacité de généralisation du modèle et conduire à un choix de k plus stable. Globalement, cette démarche illustre le cycle complet d’un problème de classification supervisée : exploration des données, préparation, choix d’un modèle, réglage d’hyperparamètres, évaluation et interprétation des résultats.
"""