# -*- coding: utf-8 -*-
"""Analyse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IczZjPSHTf6xs8it5K_LUL5JZmMXrZ8-
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
predict_students_dropout_and_academic_success = fetch_ucirepo(id=697)

# data (as pandas dataframes)
X = predict_students_dropout_and_academic_success.data.features
y = predict_students_dropout_and_academic_success.data.targets

# metadata
print(predict_students_dropout_and_academic_success.metadata)

# variable information
print(predict_students_dropout_and_academic_success.variables)

# ============================================================================
# ANALYSE STATISTIQUE COMPLÈTE - STUDENT DROPOUT AND ACADEMIC SUCCESS
# ============================================================================

# Installation et importation des bibliothèques nécessaires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import t
import warnings
warnings.filterwarnings('ignore')

# Configuration de l'affichage
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
pd.set_option('display.max_columns', None)
pd.set_option('display.precision', 3)

print("="*80)
print("ANALYSE STATISTIQUE - PRÉDICTION DU DÉCROCHAGE SCOLAIRE")
print("="*80)

# ============================================================================
# CHARGEMENT DES DONNÉES
# ============================================================================
print("\n📊 CHARGEMENT DES DONNÉES...")
from ucimlrepo import fetch_ucirepo

# Fetch dataset
predict_students_dropout_and_academic_success = fetch_ucirepo(id=697)

# Data (as pandas dataframes)
X = predict_students_dropout_and_academic_success.data.features
y = predict_students_dropout_and_academic_success.data.targets

# Fusion des données pour l'analyse complète
df = pd.concat([X, y], axis=1)

print(f"✓ Données chargées avec succès!")
print(f"  - Nombre d'observations: {df.shape[0]}")
print(f"  - Nombre de variables: {df.shape[1]}")
print(f"  - Variables features: {X.shape[1]}")
print(f"  - Variable cible: {y.columns[0]}")

# ============================================================================
# 1. STATISTIQUES DESCRIPTIVES
# ============================================================================
print("\n" + "="*80)
print("1. STATISTIQUES DESCRIPTIVES")
print("="*80)

# Sélection des variables numériques
numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
print(f"\n📈 Nombre de variables numériques: {len(numeric_cols)}")

# --- 1.1 MESURES DE TENDANCE CENTRALE ---
print("\n" + "-"*80)
print("1.1 MESURES DE TENDANCE CENTRALE")
print("-"*80)

tendance_centrale = pd.DataFrame({
    'Moyenne': X[numeric_cols].mean(),
    'Médiane': X[numeric_cols].median(),
    'Mode': X[numeric_cols].mode().iloc[0] if len(X[numeric_cols].mode()) > 0 else np.nan
})

print("\n📊 Résumé des mesures de tendance centrale:")
print(tendance_centrale.head(10))

# --- 1.2 MESURES DE DISPERSION ---
print("\n" + "-"*80)
print("1.2 MESURES DE DISPERSION")
print("-"*80)

dispersion = pd.DataFrame({
    'Variance': X[numeric_cols].var(),
    'Écart-type': X[numeric_cols].std(),
    'Étendue': X[numeric_cols].max() - X[numeric_cols].min(),
    'Q1': X[numeric_cols].quantile(0.25),
    'Q3': X[numeric_cols].quantile(0.75),
    'IQR (Q3-Q1)': X[numeric_cols].quantile(0.75) - X[numeric_cols].quantile(0.25)
})

print("\n📊 Résumé des mesures de dispersion:")
print(dispersion.head(10))

# --- 1.3 STATISTIQUES COMPLÈTES ---
print("\n" + "-"*80)
print("1.3 STATISTIQUES COMPLÈTES (describe)")
print("-"*80)

stats_completes = X[numeric_cols].describe()
print("\n📊 Statistiques descriptives complètes:")
print(stats_completes.iloc[:, :5])  # Afficher les 5 premières colonnes

# --- 1.4 ANALYSE DE LA VARIABLE CIBLE ---
print("\n" + "-"*80)
print("1.4 ANALYSE DE LA VARIABLE CIBLE")
print("-"*80)

print(f"\n🎯 Variable cible: {y.columns[0]}")
print("\nDistribution des classes:")
print(y[y.columns[0]].value_counts())
print("\nProportions (%):")
print(y[y.columns[0]].value_counts(normalize=True) * 100)

# ============================================================================
# 2. VISUALISATION GRAPHIQUE DES STATISTIQUES DESCRIPTIVES
# ============================================================================
print("\n" + "="*80)
print("2. VISUALISATION GRAPHIQUE DES STATISTIQUES DESCRIPTIVES")
print("="*80)

# --- 2.1 DISTRIBUTION DE LA VARIABLE CIBLE ---
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
fig.suptitle('Distribution de la Variable Cible', fontsize=16, fontweight='bold')

# Graphique en barres
y[y.columns[0]].value_counts().plot(kind='bar', ax=axes[0], color=['#3498db', '#e74c3c', '#2ecc71'])
axes[0].set_title('Nombre d\'étudiants par catégorie')
axes[0].set_xlabel('Statut')
axes[0].set_ylabel('Fréquence')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(True, alpha=0.3)

# Graphique en camembert
y[y.columns[0]].value_counts().plot(kind='pie', ax=axes[1], autopct='%1.1f%%',
                                     colors=['#3498db', '#e74c3c', '#2ecc71'])
axes[1].set_title('Proportion des catégories')
axes[1].set_ylabel('')

plt.tight_layout()
plt.show()

# --- 2.2 HISTOGRAMMES DES VARIABLES NUMÉRIQUES CLÉS ---
print("\n📊 Génération des histogrammes...")

# Sélection de 9 variables clés pour visualisation
vars_cles = numeric_cols[:9]

fig, axes = plt.subplots(3, 3, figsize=(18, 12))
fig.suptitle('Distributions des Variables Numériques Clés', fontsize=16, fontweight='bold')

for idx, col in enumerate(vars_cles):
    row = idx // 3
    col_idx = idx % 3
    ax = axes[row, col_idx]

    X[col].hist(bins=30, ax=ax, color='skyblue', edgecolor='black', alpha=0.7)
    ax.set_title(f'{col}', fontsize=10, fontweight='bold')
    ax.set_xlabel('Valeur')
    ax.set_ylabel('Fréquence')
    ax.grid(True, alpha=0.3)

    # Ajouter une ligne verticale pour la moyenne
    mean_val = X[col].mean()
    ax.axvline(mean_val, color='red', linestyle='--', linewidth=2, label=f'Moyenne: {mean_val:.2f}')
    ax.legend(fontsize=8)

plt.tight_layout()
plt.show()

# --- 2.3 BOÎTES À MOUSTACHES (BOXPLOTS) ---
print("\n📊 Génération des boîtes à moustaches...")

fig, axes = plt.subplots(3, 3, figsize=(18, 12))
fig.suptitle('Boîtes à Moustaches - Détection des Valeurs Aberrantes', fontsize=16, fontweight='bold')

for idx, col in enumerate(vars_cles):
    row = idx // 3
    col_idx = idx % 3
    ax = axes[row, col_idx]

    X[col].plot(kind='box', ax=ax, color='lightblue', patch_artist=True)
    ax.set_title(f'{col}', fontsize=10, fontweight='bold')
    ax.set_ylabel('Valeur')
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# --- 2.4 MATRICE DE CORRÉLATION ---
print("\n📊 Génération de la matrice de corrélation...")

# Calculer la matrice de corrélation pour les 10 premières variables
vars_correlation = numeric_cols[:10]
correlation_matrix = X[vars_correlation].corr()

fig, ax = plt.subplots(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, square=True, linewidths=1, cbar_kws={"shrink": 0.8}, ax=ax)
ax.set_title('Matrice de Corrélation des Variables Numériques', fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

# ============================================================================
# 3. STATISTIQUES INFÉRENTIELLES
# ============================================================================
print("\n" + "="*80)
print("3. STATISTIQUES INFÉRENTIELLES")
print("="*80)

# --- 3.1 INTERVALLES DE CONFIANCE À 95% ---
print("\n" + "-"*80)
print("3.1 INTERVALLES DE CONFIANCE À 95% POUR LES MOYENNES")
print("-"*80)

def calculate_confidence_interval(data, confidence=0.95):
    """
    Calcule l'intervalle de confiance pour la moyenne d'une série

    Formule: x̄ ± t(α/2) × (s/√n)
    """
    n = len(data)
    mean = np.mean(data)
    std_err = stats.sem(data)  # Erreur standard de la moyenne
    margin = std_err * t.ppf((1 + confidence) / 2, n - 1)

    return mean, mean - margin, mean + margin, margin

# Calcul des intervalles de confiance pour les variables clés
print("\n📊 Intervalles de confiance (95%) pour les variables clés:\n")

ic_results = []
for col in vars_cles:
    mean, ci_lower, ci_upper, margin = calculate_confidence_interval(X[col].dropna())
    ic_results.append({
        'Variable': col,
        'Moyenne': mean,
        'IC_Inférieur': ci_lower,
        'IC_Supérieur': ci_upper,
        'Marge_Erreur': margin
    })
    print(f"{col:30s} : {mean:8.3f} ± {margin:.3f}  [{ci_lower:.3f}, {ci_upper:.3f}]")

ic_df = pd.DataFrame(ic_results)

# --- 3.2 VISUALISATION DES INTERVALLES DE CONFIANCE ---
print("\n📊 Génération de la visualisation des intervalles de confiance...")

fig, ax = plt.subplots(figsize=(12, 8))

y_pos = np.arange(len(ic_df))
ax.barh(y_pos, ic_df['Moyenne'], xerr=ic_df['Marge_Erreur'],
        color='steelblue', alpha=0.7, capsize=5, error_kw={'linewidth': 2})

ax.set_yticks(y_pos)
ax.set_yticklabels(ic_df['Variable'], fontsize=10)
ax.set_xlabel('Valeur', fontsize=12, fontweight='bold')
ax.set_title('Intervalles de Confiance à 95% pour les Moyennes',
             fontsize=14, fontweight='bold', pad=20)
ax.grid(True, alpha=0.3, axis='x')
ax.axvline(0, color='red', linestyle='--', linewidth=1, alpha=0.5)

plt.tight_layout()
plt.show()

# --- 3.3 TESTS D'HYPOTHÈSE : COMPARAISON ENTRE GROUPES ---
print("\n" + "-"*80)
print("3.3 TESTS D'HYPOTHÈSE - COMPARAISON ENTRE GROUPES")
print("-"*80)

# Séparer les données par statut (cible)
target_col = y.columns[0]
groups = y[target_col].unique()

print(f"\n🎯 Comparaison des moyennes entre les groupes de '{target_col}'")
print(f"Groupes identifiés: {groups}")

# Test ANOVA pour une variable exemple
var_test = vars_cles[0]
print(f"\n📊 Test ANOVA pour la variable: {var_test}")

group_data = [X[var_test][y[target_col] == group].dropna() for group in groups]
f_stat, p_value = stats.f_oneway(*group_data)

print(f"  - Statistique F: {f_stat:.4f}")
print(f"  - Valeur p: {p_value:.4f}")

if p_value < 0.05:
    print(f"  ✓ Conclusion: Il existe une différence significative entre les groupes (p < 0.05)")
else:
    print(f"  ✗ Conclusion: Pas de différence significative entre les groupes (p ≥ 0.05)")

# --- 3.4 COMPARAISONS MULTIPLES ---
print("\n" + "-"*80)
print("3.4 STATISTIQUES PAR GROUPE")
print("-"*80)

print(f"\n📊 Statistiques de {var_test} par groupe:\n")

stats_by_group = pd.DataFrame({
    'Groupe': groups,
    'Moyenne': [X[var_test][y[target_col] == g].mean() for g in groups],
    'Écart-type': [X[var_test][y[target_col] == g].std() for g in groups],
    'Médiane': [X[var_test][y[target_col] == g].median() for g in groups],
    'N': [X[var_test][y[target_col] == g].count() for g in groups]
})

print(stats_by_group)

# Visualisation
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
fig.suptitle(f'Comparaison de {var_test} par Groupe', fontsize=14, fontweight='bold')

# Boxplot
for idx, group in enumerate(groups):
    data = X[var_test][y[target_col] == group].dropna()
    axes[0].boxplot([data], positions=[idx], labels=[group], widths=0.6)

axes[0].set_title('Boîtes à Moustaches par Groupe')
axes[0].set_xlabel('Groupe')
axes[0].set_ylabel(var_test)
axes[0].grid(True, alpha=0.3)

# Barplot avec erreur standard
axes[1].bar(range(len(groups)), stats_by_group['Moyenne'],
            yerr=stats_by_group['Écart-type'], capsize=10,
            color=['#3498db', '#e74c3c', '#2ecc71'], alpha=0.7)
axes[1].set_xticks(range(len(groups)))
axes[1].set_xticklabels(groups, rotation=45)
axes[1].set_title('Moyennes par Groupe (± écart-type)')
axes[1].set_xlabel('Groupe')
axes[1].set_ylabel(f'Moyenne de {var_test}')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ============================================================================
# RÉSUMÉ FINAL
# ============================================================================
print("\n" + "="*80)
print("RÉSUMÉ DE L'ANALYSE")
print("="*80)

print(f"""
📊 STATISTIQUES DESCRIPTIVES:
   - {len(numeric_cols)} variables numériques analysées
   - Mesures de tendance centrale calculées (moyenne, médiane, mode)
   - Mesures de dispersion calculées (variance, écart-type, IQR)

📈 VISUALISATIONS GÉNÉRÉES:
   - Distribution de la variable cible
   - Histogrammes des variables clés
   - Boîtes à moustaches pour détection d'outliers
   - Matrice de corrélation

🔬 STATISTIQUES INFÉRENTIELLES:
   - Intervalles de confiance à 95% calculés
   - Test ANOVA effectué pour comparaison entre groupes
   - Statistiques par groupe générées

✅ ANALYSE COMPLÈTE TERMINÉE!
""")

print("="*80)